# noinspection SpellCheckingInspection
abbreviations = {
    'a.': 'active',
    'act.': 'active',
    'abbrev.': 'abbreviated',
    'abl.': 'ablative',
    'absol.': 'absolute',
    'abs.': 'absolute',
    'abstr.': 'abstract',
    'access.': 'accessory',
    'ad loc.': 'ad locum',
    'ad h. l.': 'ad hoc locum',
    'adj.': 'adjective',
    'agric.': 'agricultural',
    'agricult.': 'agricultural',
    'a. h. v.': 'ad hanc vocem',
    'al.': 'others',
    'alii': 'others',
    'alia': 'others',
    'amplif.': 'amplificative',
    'analog.': 'analogous',
    'antiq.': 'antiquities',
    'ap.': 'apud',
    'appel.': 'appelative',
    'append.': 'appendix',
    'app.': 'appendix',
    'Arab.': 'Arabic',
    'archit.': 'architecture',
    'art.': 'article',
    'aug.': 'augmentative',
    'Aug.': 'Augustan',
    'c.': 'with',
    'c c.': 'coupled with',
    'cf.': 'confer',
    'chh.': 'church',
    'class.': 'classic',
    'Cod.': 'Codex',
    'collat.': 'collateral',
    'collect.': 'collective',
    'comm.': 'common gender',
    'commentt.': 'commentators',
    'compd.': 'compound',
    'concr.': 'concrete',
    'constr.': 'construction',
    'corresp.': 'corresponding',
    'dat.': 'dative',
    'decl.': 'declension',
    'demonstr.': 'demonstrative',
    'dem.': 'demonstrative',
    'dep.': 'deponent',
    'deriv.': 'derivation',
    'diff.': 'different',
    'dim.': 'diminutive',
    'dissyl.': 'disyllabic',
    'distr.': 'distributive',
    'dub.': 'doubtful',
    'eccl.': 'ecclesiastical',
    'ed.': 'edit.',
    'e.g.': 'exempli gratia',
    'ellipt.': 'elliptical',
    'elsewh.': 'elsewhere',
    'epic.': 'epicene',
    'epit.': 'epitaph',
    'equiv.': 'equivalent',
    'esp.': 'especially',
    'etym.': 'etymology',
    'euphon.': 'euphony',
    'ex.': 'example',
    'exs.': 'examples',
    'expl.': 'explanation',
    'ext.': 'externa',
    'extr.': 'extremo',
    'f.': 'feminine',
    'fem.': 'feminine',
    'fig.': 'figurative',
    'fin.': 'at the end',
    'ad fin.': 'at the end',
    'finit.': 'finite',
    'foll.': 'following',
    'fr.': 'from',
    'Fr.': 'French',
    'fragm.': 'fragments',
    'frgm.': 'fragments',
    'fut.': 'future',
    'geog.': 'geography',
    'Germ.': 'German',
    'Goth.': 'Gothic',
    'gr.': 'grammar',
    'gram.': 'grammar',
    'Gr.': 'Greek',
    'h.': 'hence',
    'h.l.': 'hic locus',
    'h.v.': 'this word',
    'h.vv.': 'this words',
    'Heb.': 'Hebrew',
    'hibr.': 'hybrid',
    'hist.': 'history',
    'ib.': 'ibidem',
    'id.': 'idem',
    'i.q.': 'idem quod',
    'imper.': 'imperative',
    'imperf.': 'imperfect',
    'impers.': 'impersonal',
    'inanim.': 'inanimate',
    'inch.': 'inchoative',
    'indecl.': 'indeclinable',
    'indef.': 'indefinite',
    'indic.': 'indicative',
    'inf.': 'infinitive',
    'init.': 'at the beginning',
    'in.': 'at the beginning',
    'ad init.': 'at the beginning',
    'inscrr.': 'inscriptions',
    'intens.': 'intensive',
    'intr.': 'intransitive',
    'Ital.': 'Italian',
    'JCtus.': 'juris consultus',
    'jurid.': 'juridical',
    'kindr.': 'kindred',
    'l.c.': 'loco citato',
    'l.l.': 'loco laudato',
    'lang.': 'language',
    'Lat.': 'Latin',
    'leg.': 'legit',
    'lex.': 'lexicon',
    'lit.': 'literal',
    'Lith.': 'Lithuanian',
    'm.': 'masculine',
    'masc.': 'masculine',
    'math.': 'mathematics',
    'med.': 'medio',
    'medic.': 'medical',
    'metaph.': 'metaphorical',
    'meton.': 'by metonymy',
    'milit.': 'military',
    'MS.': 'manuscript',
    'MSS.': 'manuscripts',
    'n.': 'neuter',
    'neutr.': 'neuter',
    'n.pr.': 'nomen proprium',
    'nom.propr.': 'nomen proprium',
    'naut.': 'nautical',
    'neg.': 'negative',
    'no.': 'numero',
    'nom.': 'nominative',
    'num.': 'numeral',
    'numer.': 'numeral',
    'obj.': 'objective',
    'object.': 'objective',
    'obl.': 'oblique',
    'om.': 'omit',
    'onomat.': 'onomatopoeia',
    'orig.': 'originally',
    'p.': 'page',
    'P. a.': 'participial adjective',
    'part.': 'participle',
    'partit.': 'partitive',
    'patr.': 'patronymic',
    'per.': 'period',
    'perf.': 'perfect',
    'perh.': 'perhaps',
    'pers.': 'personal',
    'philos.': 'philosophy',
    'pl.': 'plural',
    'plur.': 'plural',
    'pleon.': 'pleonastically',
    'plqpf.': 'plusquamperfectum',
    'plur.tant.': 'plurale tantum',
    'poet.': 'poetical',
    'polit.': 'political',
    'poss.': 'possessive',
    'praef.': 'praefatio',
    'praep.': 'preposition',
    'prep.': 'preposition',
    'preced.': 'preceding',
    'pregn.': 'pregnant',
    'pres.': 'present',
    'prob.': 'probably',
    'prol.': 'prologus',
    'pron.': 'pronoun',
    'prooem.': 'prooemium',
    'prop.': 'proper',
    'prov.': 'proverbial',
    'proverb.': 'proverbial',
    'qs.': 'quasi',
    'q.v.': 'quod videas',
    'rad.': 'radical',
    'rar.': 'rare',
    'ref.': 'reference',
    'respect.': 'respectus',
    'Rom.': 'Roman',
    'saep.': 'saepe',
    'saepis.': 'saepissime',
    'sc.': 'scilicet',
    's.h.v.': 'sub hac voce',
    's.v.': 'sub voce',
    'simp.': 'simple',
    'Span.': 'Spanish',
    'specif.': 'specifically',
    'sq.': 'sequens',
    'sqq.': 'sequentes',
    'subj.': 'subjunctive',
    'subst.': 'substantive',
    'suff.': 'suffix',
    'syll.': 'syllable',
    'syn.': 'synonym',
    'sync.': 'syncopated',
    'tab.': 'tabula',
    'trag.': 'tragic',
    'trans.': 'translation',
    'trisyl.': 'trisyllable',
    'trop.': 'in a figurative sense',
    't.t.': 'technical form',
    't. t.': 'technical form',
    'usu.': 'usual',
    'v. n.': 'intransitive verb',
    'v. a.': 'transitive verb',
    'v.h.c.': 'vide hanc vocem',
    'var. lect.': 'varia lectio',
    'vb.': 'verb',
    'voc.': 'vocative'
}
