# noinspection SpellCheckingInspection
fake_itypes = [
    'Ritschl',
    'and',
    'aliquis',
    'or separate',
    'or, separated',
    'Baiter',
    'Kayser',
    'commodus',
    'creber',
    'better separately',
    'Dietsch',
    'like arbos, labos',
    'communis',
    'concinnus',
    'or, separately',
    'for me',
    'neglego',
    'propero',
    'significat demito vel auferto',
    'est a grege ducere',
    'abscondo',
    'absolvo',
    'abstineo',
    'a Latin root, denoting',
    'accuro',
    'acuo',
    'ovis vetula recentis partus',
    'more properly ad instar',
    'adulor',
    'for usque ad',
    'of Verona',
    'for abfore and abforem',
    'oppidum',
    'another reading for Alius',
    'but if they are genuine',
    'amo',
    'appellatur, qui aduncum bracchium habet et exporrigi non potest',
    'animo',
    'whence antidea, antideo',
    'better written separately',
    'like antidea for antea, and antideo for anteeo',
    'more correctly',
    'an ancient word for valde',
    'a form of apud',
    'infelix',
    'like arquus for arcus, quur for cur',
    'aqua, quae inferis libabatur',
    'est vas, in quo prandium fertur, ut discus',
    'regio',
    'Holder',
    'Baiter, Halm',
    'Lachmann',
    'others except Halm',
    'Kayser, Halm',
    'Ritschl, Fleckeisen',
    'Ritschl, Baiter',
    'Ritschl, Lachmann',
    'Halm',
    'Ritschl, Baiter, Halm, Jahn',
    'also several times repeated, atatatae, attatatatae, or atatte, atattate',
    'mons',
    'ulmus',
    'auro',
    'like oricula for auricula',
    'mulieres sive viri dicebantur unā agentes',
    'terra',
    'nŭces',
    'constat dimetro',
    'used by Augustus for stultus',
    'sonus ex ore cornicinis lituum eximentis',
    'bullas luti ex itineribus, aut quod calceamentorum soleis eraditur appellabant',
    'non nisi singularem numerum capit, nam pluralem nemo dixit',
    'est menstruo mulierum sanguine inquinare',
    'an old form for Pyrrhus',
    'hasta',
    'and in poetry equally common',
    'suffusi equi',
    'dicit',
    'calce polita',
    'Montes',
    'pistor',
    'species stativi auguril, cum auspicato arbor capitur et consecratur Jovis fulguri',
    'marinos equos Graeci a flexu',
    'NEGOTIATOR',
    'like codex, plostrum',
    'an inseparable strengthening demonstrative particle',
    'locus',
    'in carmine Saliari intellegitur creator',
    'like claudo and clodo, codex and caudex, plostrum and plaustrum',
    'cingere',
    'on account of a derivation from cloaca',
    'nobilior',
    'culter',
    'acus, quibus mulieres caput scalpunt',
    'cognosco',
    'porcus dicitur, qui cibo permixto et colluvie nutritur',
    'like arbos, clamos, honos',
    'Lymphae, ad lacum Cutiliensem a commotu, quod ibi insula in aquā commovetur',
    'for convocanto',
    'in quo omnibus dīs communiter sacrificabatur',
    'coauditum, sicut conangustatum dicitur',
    'a corrupt word',
    'dicebantur, quae sub eādem erant clave',
    'another orthography for chondrille',
    'occulta',
    'sacra',
    'hominum',
    'contineo',
    'sunt in angustum coacti conniventibus palpebris',
    'ac',
    'apud antiquos pro adverbio, quod est profecto, ponebatur',
    'divarum locus erat trans Tiberim cornicibus dicatus, quod in Junonis tutelā esse putabantur',
    'old form for committere',
    'Tabernae',
    'aqua',
    'apud Ennium significat vallum crebris suris id est palis munitum',
    'qui eodem tempore erant nati',
    'valde exile',
    'genus operis pistorii',
    'cortices nucum viridium, dicta a similitudine culeorum, quibus vinum sive oleum continetur',
    'fusticulus quidam ligneus in sacris dicebatur',
    'significat cum altero, dictum ab antiquis ita brevitatis causā, ut sodes pro si audes, scilicet pro scias licet, '
    'sis pro si vis',
    'est stercus facere',
    'mensae, in quibus immolabatur Junoni, quae curis appellata est',
    'vas, quo in sacrificiis vinum fundebatur',
    'words of a charm to cure a dislocated joint',
    'is a corruption of late Latin',
    'calce litum',
    'togae detritae',
    'valde occultarunt',
    'a fomitibus succisum, quibus confoveri erat solitum lignum',
    'detrita atque detonsa',
    'like clodo, codex, clostrum, plostrum',
    'est descindere et quasi lanam trahere',
    'or in two words, de longe',
    'valde magis',
    'perorata',
    'senes appellabantur, qui sexagenarii de ponte deiciebantur',
    'dirigo',
    'desinere',
    'destino',
    'porcae id est macilentae',
    'dicitur qui imprecatur',
    'genus purpurae',
    'differo',
    'diffido',
    'signa imponunt, ut fieri solet in pecoribus',
    'genus piscis frequens in Ponto',
    'an inseparable particle',
    'dicuntur',
    'tribus',
    'insulae',
    'certus',
    'citer',
    'adnominatio, adnosco',
    'hostiae',
    'like honos, labos, colos',
    'vicus',
    'Merkel',
    'balux',
    'lăcus',
    'used by Augustus for languere',
    'divisiones patrimoniorum inter consortes',
    'a false reading for discidium',
    'another form of dissaeptum',
    'porcus dicitur, cum in cervice setas dividit',
    'less correct form for dicio',
    'antiqui dicebant, quae nunc sunt castella, ex quibus a rivo communi aquam quisque in suum fundum ducit',
    'doleo',
    'dominor',
    'like Alcumena, Aesculapius',
    'apud antiquos dicebatur qui nunc dominus',
    'dicebatur cum altero, id est, cum filio census',
    'like Casmena, Casmili',
    'exertum, quod scilicet omnes exerto brachio sint exfilati, id est extra vestimentum filo contextum',
    'vocari veteri more solet hostia, quae ad aras adducta est immolanda, si casu effugeret',
    'plus quam nominare',
    'antiqui dicebant pro accipere',
    'paganorum dea',
    'mercenarium',
    'false reading for navatae',
    'etiamne',
    'genus vilissimi unguenti',
    'Galli bonos equorum domitores vocant',
    'jusjurandum per Quirinum',
    'for erit',
    'for erunt',
    'for editur',
    'lineum filum, quod medici extremo in clysterio relinquunt',
    'false reading for eureos',
    'dictus, quod ex una parte habeat Eurum, ab altera Austrum',
    'eventilatum, unde velabra, quibus frumenta ventilantur',
    'vocatur, qui jure accepta hereditate justa facere defuncto debet, quae si non fecerit, seu quid in ea re '
    'turbaverit',
    'exinteratas',
    'excello',
    'quod excipitur, ut prae cipuum quod ante capitur',
    'exuviae',
    'purgamentum, unde adhuc manet suffitio',
    'causa, quae adversus exsulem agitur',
    'sunt comici vestitus exsertis humeris',
    'in locum patentem se dare, sive in spatium se conferre',
    'est ex lege vetere aliquid eximere per novam legem',
    'terram palustrem vocabant',
    'dicito',
    'Julia',
    'vocabantur, qui depellere fascinum credebantur',
    'palus ficulneus',
    'a fide denominata, ea quae maximae fidei erant',
    'faber',
    'fibulas',
    'dicebantur genus hominum, quod mercede flagris caedebantur',
    'myrrha',
    'dictum, quod eo die spicae feruntur ad sacrarium',
    'fluo',
    'foculi, a fovendo, id est calefaciendo, dicta sunt',
    'appellatur pars remi, quae folliculo est tecta, a quo vita follicularis',
    'antiqui omne genus cibi appellabant',
    'forcipes dictae, quod forma capiant, id est ferventia',
    'but rarely',
    'qui nunc Favii dicuntur',
    'displicebunt',
    'villi sordidi in tapetis',
    'puerorum mammae dicuntur, cum primum tumescunt',
    'uxor fratris',
    'est Graecum vocabulum partis hominum, ut Neapoli etiam nunc',
    'personified',
    'a frugibus appellata',
    'arguere est',
    'a galearum similitudine dicta',
    'canum querula murmuratio',
    'and its derivatives',
    'tibicen',
    'mensae gliscentes, id est crescentes, per instructionem epularum scilicet',
    'gallinarum proprium est, cum ovis incubiturae sunt',
    'significat apud Livium',
    'a name comically formed',
    'funis crassus',
    'nucum juglandium summa et viridia putamina',
    'significat omnia mentientem',
    'id est hesterno vino languentem',
    'alii piscatores, alii, qui unco cadavera trahunt',
    'parva delubra, quasi fanula',
    'before consonants',
    'genus ornamenti Lydii, dictum a colore boum, qui est inter rufum et album appellaturque helvus',
    'antiqui accepta hereditate colebant, quae a nomine appellabatur heredum, et esse una ex Martis comitibus '
    'putabatur',
    'res minimi pretii, quasi hieta',
    'lascivi et delicati carminis cantator',
    'naves, quibus equi vehuntur',
    'vinum ex insula Coo dictum ab agro generoso, cui nomen est Hippo',
    'durorum pilorum homines',
    'latro atque obsessor viarum',
    'pilei genus',
    'pro bono dicebant',
    'hostium captor',
    'like illoc, istoc',
    'a false reading for Lasus',
    'the ninth letter of the Latin alphabet',
    'vitium vasorum fictilium',
    'alii pro vincto utuntur, alii pro soluto',
    'et aliorsum sicut introrsum dixit Cato',
    'barbatum fieri',
    'fictum ab urvo, quod ita flexum ut redeat sursum vorsus, ut in aratro quod est urvum',
    'incunctanter',
    'non parentem hoc est obedientem',
    'cujus ultimum penetrale intrare non licet',
    'agnae, in Saliari carmine spicas significat sine aristis',
    'quasi imponimenta, quae post cenam mensis imponebant',
    'est qui nondum vir est',
    'qui nondum esset ascriptus in civitate',
    'stupratus, impudicus factus',
    'virgula erat ex malo Punico incurvata, quam regina sacrificans in capite gestabat',
    'invocanto',
    'invocationes',
    'vocative',
    'per despectum irrisio',
    'muliebre ministerium',
    'machinula, in qua constituebatur in convivio vini amphora, de qua subinde deferrentur vina',
    'sine comite',
    'for usual crepundia',
    'for in dies',
    'false reading for inductor',
    'false reading for inductis',
    'false reading for in effusum',
    'eo ipso',
    'armis spoliat',
    'for infectus',
    'non fateri',
    'false reading for ingenioque',
    'false reading for in gravi',
    'false reading for oreretur',
    'false reading for increscente',
    'me',
    'inhibenti',
    'deinceps',
    'false reading for insiticius',
    'false reading for in sativis',
    'false reading for in perficiendo',
    'false reading for non vidit',
    'false reading for involucri',
    'ipsi neque alii',
    'bracteae in virilem muliebremque speciem expressae',
    'genus farciminis in sacrificiis',
    'verbum',
    'Portus',
    'a consonant which',
    'qui frequenter jacturam patitur',
    'active form of the following',
    'the strengthened jam',
    'juris actio',
    'for hyoscyamus',
    'like arbos, honos',
    'an old form for lacrima',
    'not lacrўma',
    'an imprecation',
    'vestimenti genus ex lana sucida confectum',
    'qui lana tegit oculi vitium',
    'fures antiqui dicebant, quod sub tutela deae Lavernae essent, in cujus luco obscuro abditoque solitos furta '
    'praedamque inter se luere',
    'for liber',
    'ornamenta tunicarum aurea',
    'appellantur instrumenta bellica saxa scilicet ad bracchii crassitudinem in modum flagellorum loris revincta',
    'a lengthened form of limen, assumed as accounting for the form postliminium',
    'sic dicitur, sicut dextrorsus, sinistrorsus',
    'the twelfth letter of the Latin alphabet',
    'linguā Oscā, mensis Maius',
    'persona comica ab inventore dicta',
    'like ejjus, pejjus',
    'appellatur loro circumvolutum mediocris longitudinis lignum rotundum, quod circumagunt fabri in operibus '
    'tornandis',
    'also Genita Mana',
    'fallacia vel lenocinium',
    'diminutivum a Marco',
    'Sabinus',
    'edacem a mandendo scilicet',
    'cognominantur homines malarum magnarum atque oribus late patentibus',
    'for mihi',
    'medicabile',
    'velum quod in prora ponitur',
    'dicebant, quod nos commentum',
    'mercenarium, quod mercede se tueatur',
    'for merx',
    'a pronominal suffix attached to substantive and',
    'for minium',
    'for mihine',
    'pro minimo dixerunt',
    'like magester, leber',
    'pro reminiscitur antiquitus dicebatur',
    'for minime',
    'for minimus',
    'appellantur avium minorum cantus',
    'primae adulescentiae',
    'appellantur, qui non certae sunt sententiae, sed variorum mixtorumque judiciorum sunt',
    'false reading for mellita',
    'for munia',
    'for meta',
    'a false reading for mormorion',
    'dici solet a Castrensium hominibus, quasi mucosus, is, qui talis male ludit',
    'or, archaic',
    'false reading for illutibarbus',
    'pro communicas dicebant',
    'archaic form',
    'had its full',
    'nec eum',
    'non eunt',
    'also separately',
    'annuale tributum, quod certo tempore rustici dominis, vel discipuli doctoribus afferre solent, duntaxat sit '
    'carneum, ut porcellus'
    'false read, for noenu and noenum',
    'detrimenta',
    'pro sine positum est in lege dedicationis arae Dianae Aventinensis',
    'a mutilated epithet of cassia',
    'more correctly separate',
    'pro nobis',
    'Lex Rubria',
    'vocantur papillae, quae ex faucibus caprarum suppendent',
    'or better separately',
    'et sescunciam quod magistri ludi appellant, significat dodrantem et dimidium teruncium, quod singula sescuncia '
    'uncia et dimidium sit',
    'for notor',
    'more correctly written separate',
    'Ateius Philologus ait appellari solitum',
    'the fourteenth letter of the Latin alphabet',
    'exacerbat',
    'herbam increscere',
    'dicebant antiqui mente errasse, quasi in luco deorum alicui occurrisse',
    'pro diu manens, ut permanens',
    'obligare, maxime in nuptiis frequens est',
    'se offerre salutandi gratiā dicebant antiqui, ut consalutare, persalutare',
    'dicebant antiqui, quod nunc ostendit',
    'contra sententiam tractat',
    'for occedo',
    'ager dicitur, qui desertus a cultoribus propriis, ab aliis occupatur',
    'dicebant pro olfacit',
    'an ancient form for usus',
    'colorum infectores',
    'fallacias',
    'for universi',
    'for Olearos',
    'old form for ille',
    'Antistius Labeo ait esse mensurae genus',
    'mellis',
    'quasi optuitu, a verbo',
    'for primordia',
    'nymphae montium cultrices',
    'pugna in proverbio, quo significabatur, victos vincere, quia in eādem et Valerius Laevinus imperator Romanus a '
    'Pyrrho erat victus',
    'pro parte',
    'and, only in inscriptions',
    'compactio, unde compages et propagare',
    'a false reading for pharnuprius',
    'dicebatur dies idem et communicarius, in quo omnibus diis communiter sacrificabatur',
    'and, corrupted',
    'et oves et gallinae appellantur, quod passim pascuntur',
    'an enclitic particle with an intensive force',
    'another reading for pedicellus',
    'qui pellicit ad fraudem',
    'for pereo',
    'perfringas',
    'another reading for parapeteuma',
    'in Saliari carmine Aelius Stilo dici ait capitia ex pellibus agninis facta, quod Graeci pelles vocent pesce '
    'neutro genere pluraliter',
    'significare videtur pestilentiam',
    'for pennis',
    'malus',
    'appellant Graeci, quas vulgus peras vocat',
    'false reading for Phalaceus',
    'in carmine Saliari Romani, velut pilis uti assueti, vel quia praecipue pellant hostes',
    'Osce quicquid',
    'archaic for plures, plura',
    'for plurimus',
    'poeniteo',
    'pro ulteriore',
    'for puer',
    'is used',
    'praeoptant',
    'a false reading for prognariter',
    'old form of praemonstro',
    'also separate',
    'prior',
    'mulieres privatas dicebant',
    'privis id est singulis',
    'progenies, quae ab uno capite procedit',
    'saepe prolicere, id est producere',
    'testamentum',
    'dicuntur fere velites, qui noctu custodiae causā ante castra excubant, cum castra hostium in propinquo sunt',
    'promittunt',
    'hostiae vocantur, ut ait Veranius',
    'litem promovere',
    'prodigia',
    'and, separate',
    'impetrari',
    'propositus',
    'provideo',
    'pro privignum',
    'a pronominal suffix appended to adjective and',
    'saxa esse ad portum qui sit secundum Tiberim ait Fabius Pictor',
    'for purissime',
    'a spurious reading for purpuratorum',
    'lapis',
    'the sixteenth letter of the Latin alphabet',
    'dicebantur',
    'Athenas Attius appellavit, quod scilicet ex quattuor urbibus in unam domicilia contulerunt, Braurone, Eleusine, '
    'Piraeeo, Sunio',
    'more correctly as two words',
    'ab antiquis dicebatur orcus',
    'for et quin',
    'for quibus',
    'for cujus',
    'fidicines dicti, quia videntur chordas ictu radere',
    'dicitur quasi repandum',
    'aves in auspicio dicuntur, quae acturum aliquid remorari compellunt',
    'ager dictus, qui possessus est a Remo',
    'fulgur vocatur, cum ex aliquo fulgure functio fieri coepit, si factum est simile fulgur, quod idem significet',
    'cum ait Cato, aquam eo nomine significat, quā horti irrigantur',
    'revereor',
    'incorrect spelling for Regium and Reginus',
    'montes',
    'rhŏis',
    'ab eodem',
    'abruptio',
    'ruo',
    'and per tmesin, sacroque sanctum',
    'vocati sunt, quia dum eis membrorum quaecumque partes salierint, aliquid sibi exinde prosperum seu triste '
    'significari praedicunt',
    'promontorium',
    'dicti sunt',
    'sanus',
    'sarcio',
    'and abbreviated',
    'genus herbae frugibus inimicae, quod eas velut hedera implicando necat',
    'id est pelles testium arietinorum a pellibus dicti',
    'tenue et macrum et in quo tantum exilis pellicula cernitur',
    'narrationes',
    'librum est, quod secespitā secatur',
    'false reading',
    'sedile',
    'soleae dimidiatae appellantur, quibus utebantur in venando, quo planius pedem ponerent',
    'rusticius videtur',
    'for sibi',
    'callidus sive acutus',
    'signo',
    'antiqui pro eo, quod nunc jentaculum dicimus, appellabant, quia jejuni vinum sili conditum ante meridiem '
    'absorbebant',
    'funera sunt, quibus adhibentur duntaxat ludi',
    'in omni re curiosa',
    'avis tributa Saturno ab auguribus',
    'sunt quae spectantur',
    'vocatur infra umbilicum suis, quod est carnis, proprii cujusdam habitus, exos',
    'simulacrum in foro colebatur',
    'gravis tardus, sicut Lucilius pedibus stlembum dixit equum pigrum et tardum',
    'idem ait esse sic te',
    'colos appellatur',
    'dicebantur quaedam lamellae sacrificiis necessariae',
    'quod non plane sapit',
    'ventus',
    'pagus',
    'dicebatur folliculus testium arietinorum, quo utebantur pro marsupio, forsitan dictus a fisci similitudine',
    'in composition',
    'dicebatur ab auguribus avis quae ex summo cacumine vocem emisisset, dicta ita, quia super omnia vagatur aut canit',
    'Castellum',
    'tacite',
    'legem convivalem ficto nomine conscripsit jocoso carmine Valerius Valentinus',
    'an onomatopee',
    'an onomatopee, expressing the sound of blows',
    'a pronominal suffix',
    'est jumentis maribus feminas vel mares feminis admovere, licet alii dicant testilari',
    'sodalitas',
    'genus sellae habetur apud Plautum',
    'Aelius Stilo ait noscere esse',
    'Trasimenus lacus, or simply Trasimenus',
    'vertit, unde trepido et trepidatio, quia turbatione mens vertitur',
    'ungues magnos atque asperos Cato appellavit',
    'fustis uncus',
    'perierit, dictum a vallo militari, quod fit circa castra, quod qui eo eiciuntur pro perditis habentur',
    'unda est quae ad litus venit',
    'more correctly written separately',
    'mensalia auguria',
    'et vespillones dicuntur, qui funerandis corporibus officium gerunt, non a minutis illis volucribus, sed quia '
    'vespertino tempore eos efferunt',
    'apud Plautum cena intellegitur',
    'frutecta densa dicta a similitudine vestis',
    'pili in naribus hominum, dicti quod his evulsis caput vibratur',
    'a false reading for vicies',
    'dicebant continentem',
    'ager dicitur, qui viritim populo distribuitur',
    'old forms for vult, vultis, from volo',
    'pro vos ipsi Cato posuit',
    'and, less correctly',
    'archaic form of veto',
    'a Greek letter introduced at a late period for words borrowed from the Greek',
    'was perhaps a letter of the original Latin alphabet, since it is found in the Carmen Saliare',
    'janitor',
    'annuale tributum, quod certo tempore rustici dominis, vel discipuli doctoribus afferre solent, duntaxat sit '
    'carneum, ut porcellus',
    'appellantur quidam',
    'ranae dicuntur, cum vocem mittunt',
    'cunctor',
    'quod capi potest',
    'vigiliam circuire',
    'frequentem',
    'liveo',
    'false read, for noenu and noenum',
    'pure',
    'assequi, adipisci',
    'foecunditas, foecundo, foecundus',
]