# noinspection SpellCheckingInspection
pos_tags = {
    "Adj.": "adjective",
    "adj.": "adjective",
    "P. a.": "adjective (participial)",
    "Part.": "participle",
    "Subst.": "noun",
    "adv.": "adverb",
    "adv. num.": "adverb (numeral)",
    "num. adj.": "adjective (numeral)",
    "interj.": "interjection",
    "prep.": "preposition",
    "pron. adj.": "adjective (pronominal)",
    "v.": "verb",
    "v. a.": "verb (transitive)",
    "v. a. and n.": "verb (transitive and intransitive)",
    "v. a. dep.": "verb (transitive deponent)",
    "v. a. freq.": "verb (transitive frequentative)",
    "v. a. intens.": "verb (transitive intensive)",
    "v. dep.": "verb (deponent)",
    "v. dep. a.": "verb (transitive deponent)",
    "v. dep. a. freq.": "verb (transitive frequentative deponent)",
    "v. dep. freq.": "verb (frequentative deponent)",
    "v. dep. freq. a.": "verb (transitive frequentative deponent)",
    "v. dep. inch. n.": "verb (intransitive inchoative deponent)",
    "v. dep. n.": "verb (intransitive deponent)",
    "v. freq.": "verb (frequentative)",
    "v. freq. a.": "verb (transitive frequentative)",
    "v. freq. a. and n.": "verb (transitive and intransitive frequentative)",
    "v. freq. a. dep.": "verb (transitive frequentative deponent)",
    "v. freq. dep.": "verb (frequentative deponent)",
    "v. freq. dep. a.": "verb (transitive frequentative deponent)",
    "v. freq. dep. n.": "verb (intransitive frequentative deponent)",
    "v. freq. n.": "verb (intransitive frequentative)",
    "v. impers.": "verb (impersonal)",
    "v. impers. inch.": "verb (impersonal inchoative)",
    "v. inch.": "verb (inchoative)",
    "v. inch. a.": "verb (transitive inchoative)",
    "v. inch. dep.": "verb (inchoative deponent)",
    "v. inch. impers.": "verb (impersonal inchoative)",
    "v. inch. n.": "verb (intransitive inchoative)",
    "v. inch. n. impers.": "verb (impersonal intransitive inchoative)",
    "v. intens.": "verb (intensive)",
    "v. intens. a.": "verb (transitive intensive)",
    "v. intens. n.": "verb (intransitive intensive)",
    "v. n.": "verb (intransitive)",
    "v. n. and a.": "verb (intransitive and transitive)",
    "v. n. dep.": "verb (intransitive deponent)",
    "v. n. freq.": "verb (intransitive frequentative)",
    "v. n. impers.": "verb (intransitive impersonal)",
    "v. n. inch.": "verb (intransitive inchoative)"
}
